# *******************************************************************
# This file was created automatically by the sample environment
# generator. Developers should use `tox -e genconfig` to update it.
# Users are recommended to make changes to a copy of the file instead
# of the original, if any customizations are needed.
# *******************************************************************
# title: Configuration for router advertisement daemon (radvd)
# description: |
#   Contains the available parameters that need to be configured when using
#   a IPv6 network. Requires the ipv6-radvd.yaml environment.
parameter_defaults:
  # The Nova flavor to use for the radvd instance
  # Type: string
  radvd_flavor: m1.small

  # The base image for the radvd instance.  A CentOS 7 image is currently
  # the only one supported.
  # Type: string
  radvd_image: CentOS-7-x86_64-GenericCloud

