---
- hosts: localhost
  tasks:
    - name: create stack
      register: stack_create
      os_stack:
        name: ovb-rhel7
        state: present
        template: "heat-templates/server.yaml"
        environment:
          - "environments/env.yaml"
        parameters:
          flavor: bmc
          image: rhel-server-7.7-update-2
